### ISSUE TITLE
资源发布未执行

### ISSUE THREAD

**Issue by manren** [laravel-admin-extensions/UEditor#1]
按装后，发布资源并没有把静态资源复制到public下，需要手动把资源粘过去，还有配置文件也是手动粘的，这块是不是有问题呢

**Comment by moore0903** [comment]
发布资源用的是超哥的,参照超哥的解释 
[https://github.com/overtrue/laravel-ueditor/issues/52](https://github.com/overtrue/laravel-ueditor/issues/52)
