### ISSUE TITLE
更新到了3.0还是不显示图片

### ISSUE THREAD

**Issue by chenzhulin** [laravel-admin-extensions/UEditor#18]
框架版本5.8

富文本编辑器使用composer升级到了3.0，还是不显示图片

插入图片时不显示

**Comment by codingyu** [comment]
提示上传失败么？打开浏览器控制台，看看上传的请求是否报错

**Comment by chenzhulin** [comment]
> 提示上传失败么？打开浏览器控制台，看看上传的请求是否报错

上传成功了，但是图片报出404

**Comment by codingyu** [comment]
没执行过？ `php artisan storage:link`

**Comment by chenzhulin** [comment]
果然是没有执行 php artisan storage:link 的问题，但是你的配置里面没有这个步骤呀




------------------ 原始邮件 ------------------
发件人: "Yu"<notifications@github.com>;
发送时间: 2019年10月6日(星期天) 中午1:23
收件人: "laravel-admin-extensions/UEditor"<UEditor@noreply.github.com>;
抄送: "菜鸟"<2655310177@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [laravel-admin-extensions/UEditor] 更新到了3.0还是不显示图片 (#18)




没执行过？ php artisan storage:link
