### ISSUE TITLE
本地测试可以显示图片，但是线上还是报错404，我是把代码压缩之后放在服务器上解压的

### ISSUE THREAD

**Issue by chenzhulin** [laravel-admin-extensions/UEditor#19]
laravel 5.8 

编辑器 3.0

**Comment by codingyu** [comment]
@chenzhulin  UEditor 切换到源码模式，看看里面的图片链接地址

**Comment by chenzhulin** [comment]
> @chenzhulin UEditor 切换到源码模式，看看里面的图片链接地址

在form表单里面怎么切换

**Comment by codingyu** [comment]
> > @chenzhulin UEditor 切换到源码模式，看看里面的图片链接地址
> 
> 在form表单里面怎么切换

![image](https://user-images.githubusercontent.com/20354841/66284134-0fbc2500-e8f9-11e9-81d8-7a1ff503a21e.png)

**Comment by chenzhulin** [comment]
> > > @chenzhulin UEditor 切换到源码模式，看看里面的图片链接地址
> > 
> > 
> > 在form表单里面怎么切换
> 
> ![image](https://user-images.githubusercontent.com/20354841/66284134-0fbc2500-e8f9-11e9-81d8-7a1ff503a21e.png)

这是源码模式
<p>
    <img src="/ueditor/php/upload/image/20191007/1570418600535892.png" title="1570418600535892.png" alt="4.png"/>
</p>
好像是上传成功之后，对应文件夹下没有对应文件

**Comment by chenzhulin** [comment]
老哥你有qq吗，或者微信也行

**Comment by chenzhulin** [comment]
> @chenzhulin UEditor 切换到源码模式，看看里面的图片链接地址

解决了，是我路径的问题，没配置好
