### ISSUE TITLE
存入中文双引号“， 再次编辑显示空白，刷新后正常显示。 ps 纯英文字符不会出现这个问题

### ISSUE THREAD

**Issue by Vfuryx** [laravel-admin-extensions/UEditor#2]
### 存入中文双引号“， 再次编辑显示空白，刷新后正常显示。 ps 纯英文字符不会出现这个问题

没有做特殊配置

存入数据库正常
<img width="710" alt="qq20181209-174349 2x" src="https://user-images.githubusercontent.com/16946029/49695919-e3eae880-fbdc-11e8-8068-6261dc591334.png">

想再次编辑数据，选中数据打开，富文本编辑器显示为空白
![7f39becb-c1e9-46ce-a413-c43a278e7be7](https://user-images.githubusercontent.com/16946029/49695923-efd6aa80-fbdc-11e8-912e-ba331400367b.png)

结构
![3c4ca22a-cc63-43a4-b5a0-92af99d04443](https://user-images.githubusercontent.com/16946029/49695925-f402c800-fbdc-11e8-814d-b33ae34cef4c.png)

当刷新浏览器后，正常显示

<img width="710" alt="qq20181209-174349 2x" src="https://user-images.githubusercontent.com/16946029/49695929-00872080-fbdd-11e8-9154-9dab5f9a72e3.png">

**Comment by codingyu** [comment]
可能是 pjax的原因导致有些js没有执行，具体的我没看，这几个月有事，没时间碰电脑，欢迎pr

**Comment by codingyu** [comment]
`script` 标签替换为 `textarea` 后没问题了
