### ISSUE TITLE
上传图片重命名问题

### ISSUE THREAD

**Issue by ljheisenberg1072** [laravel-admin-extensions/UEditor#22]
你好，我按照UEditor官网`{time}{rand:6}`重命名，但是只是多了一层这个名称的文件夹，文件名还是上传之前的文件名，这是什么原因

**Comment by codingyu** [comment]
目前还不支持

看了一下，依赖的 [overtrue/laravel-ueditor](https://github.com/overtrue/laravel-ueditor)  只能在 `config/ueditor.php` 配置是否 md5 文件名
