### ISSUE TITLE
在进行发布资源的时候，提示Unable to locate publishable resources.

### ISSUE THREAD

**Issue by andyzu** [laravel-admin-extensions/UEditor#25]
php artisan vendor:publish --provider=Codingyu\LaravelUEditor\UEditorServiceProvider
Unable to locate publishable resources.
Publishing complete.

**Comment by codingyu** [comment]
![image](https://user-images.githubusercontent.com/20354841/75985534-6faa0c80-5f27-11ea-9830-8af20289aac5.png)

这样试试呢？

**Comment by codingyu** [comment]
也可能需要加引号
`php artisan vendor:publish --provider='Codingyu\LaravelUEditor\UEditorServiceProvider'`
