### ISSUE TITLE
Please update to support laravel 7.x

### ISSUE THREAD

**Issue by zishang520** [laravel-admin-extensions/UEditor#26]
Problem 1                                                                                                                                                                       
    - codingyu/ueditor 3.0.0 requires codingyu/laravel-ueditor ~2.0 -> satisfiable by codingyu/laravel-ueditor[2.0.0].                                                            
    - Installation request for codingyu/ueditor ^3.0 -> satisfiable by codingyu/ueditor[3.0.0].                                                                                   
    - Conclusion: remove laravel/framework v7.0.4                                                                                                                                 
    - Conclusion: don't install laravel/framework v7.0.4                                                                                                                          
    - codingyu/laravel-ueditor 2.0.0 requires laravel/framework ~5.5|~6.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].               
    - Can only install one of: laravel/framework[5.5.x-dev, v7.0.4].                                                                                                              
    - Can only install one of: laravel/framework[5.6.x-dev, v7.0.4].                                                                                                              
    - Can only install one of: laravel/framework[5.7.x-dev, v7.0.4].                                                                                                              
    - Can only install one of: laravel/framework[5.8.x-dev, v7.0.4].                                                                                                              
    - Can only install one of: laravel/framework[6.x-dev, v7.0.4].                                                                                                                
    - Installation request for laravel/framework (locked at v7.0.4, required as ^7.0) -> satisfiable by laravel/framework[v7.0.4].

**Comment by codingyu** [comment]
已经更新了 `codingyu/laravel-ueditor` 的版本依赖，可以安装了
