### ISSUE TITLE
div等标签会被过滤掉的问题怎么配置

### ISSUE THREAD

**Issue by Cuifc** [laravel-admin-extensions/UEditor#27]
是不是会热加载ueditor的配置，按网上取消对html标签过滤的配置修改了ueditor.config.js和ueditor.all.js的相关配置都没作用。

**Comment by codingyu** [comment]
初始化编辑器时的配置，是在 config/amdin.php => extensions => ueditor 中配置的（或者在定义字段时传入，覆盖 admin.php 中的配置）

修改 ueditor 源码的话，跟这里初始化配置应该没有关系了

你指的这种么：div 转成了 p标签 `'allowDivTransToP' => false` 这个配置可以限制div 转 p

```
// config/amdin.php

'extensions' => [
        'ueditor' => [

            // 如果要关掉这个扩展，设置为false
            'enable' => true,

            // 编辑器的前端配置 参考：http://fex.baidu.com/ueditor/#start-config
            'config' => [
                'initialFrameHeight' => 400, // 例如初始化高度
                'allowDivTransToP' => false,
            ]
        ],
]
```

**Comment by Cuifc** [comment]
> 初始化编辑器时的配置，是在 config/amdin.php => extensions => ueditor 中配置的（或者在定义字段时传入，覆盖 admin.php 中的配置）
> 
> 修改 ueditor 源码的话，跟这里初始化配置应该没有关系了
> 
> 你指的这种么：div 转成了 p标签 `'allowDivTransToP' => false` 这个配置可以限制div 转 p
> 
> ```
> // config/amdin.php
> 
> 'extensions' => [
>         'ueditor' => [
> 
>             // 如果要关掉这个扩展，设置为false
>             'enable' => true,
> 
>             // 编辑器的前端配置 参考：http://fex.baidu.com/ueditor/#start-config
>             'config' => [
>                 'initialFrameHeight' => 400, // 例如初始化高度
>                 'allowDivTransToP' => false,
>             ]
>         ],
> ]
> ```

谢谢，已解决。暂时不知道直接修改JS文件为什么没效果
