### ISSUE TITLE
编辑中的图片能够直传七牛元吗？

### ISSUE THREAD

**Issue by kailinwo** [laravel-admin-extensions/UEditor#3]
大佬，想请问下能够在laravel-admin中配置它直接将图片上传的七牛云的对象存储中吗？

**Comment by codingyu** [comment]
这个要参考 [overtrue/laravel-ueditor](https://github.com/overtrue/laravel-ueditor) 的配置七牛了，能在 laravel-admin 配置的只是前台的一些选项

**Comment by kailinwo** [comment]
哦哦，好滴，谢谢你啦
