### ISSUE TITLE
composer.json中的require  "encore/laravel-admin": "~1.6",的配置对使用 "encore/laravel-admin": "dev-master"的人很不友好

### ISSUE THREAD

**Issue by never615** [laravel-admin-extensions/UEditor#32]
建议使用suggest，我不想在fork改这个了。。回头你这边升级又麻烦。。。

**Comment by kaodouqifei** [comment]
有没有解决啊，我也碰到这个问题了

**Comment by never615** [comment]
> 有没有解决啊，我也碰到这个问题了

只能自己改了用。
composer.json中
require写这个
 "codingyu/ueditor": "dev-develop"
然后：
![image](https://user-images.githubusercontent.com/9959927/87918931-a7b28600-caa9-11ea-89de-87b4e167404f.png)、

https://code.aliyun.com/never615/UEditor.git

**Comment by kaodouqifei** [comment]
用别名可以解决这个问题
```
{
"require": {
        "encore/laravel-admin": "dev-master as 1.8.1"
    }
}
```

**Comment by never615** [comment]
> 用别名可以解决这个问题
> 
> ```
> {
> "require": {
>         "encore/laravel-admin": "dev-master as 1.8.1"
>     }
> }
> ```

香啊，谢谢
