### ISSUE TITLE
表单联动 select when样式出错

### ISSUE THREAD

**Issue by wen-gg** [laravel-admin-extensions/UEditor#36]
如图，联动选择时，宽高样式没有了
![image](https://user-images.githubusercontent.com/17865026/98922355-507b6a00-250d-11eb-9dfd-5476d455587c.png)
![image](https://user-images.githubusercontent.com/17865026/98922361-52452d80-250d-11eb-81b6-509b1c0dd804.png)

**Comment by wzlzking** [comment]
请问解决了吗

**Comment by wen-gg** [comment]
> 请问解决了吗

动态替换了样式
