### ISSUE TITLE
编辑器二次加载的问题

### ISSUE THREAD

**Issue by moore0903** [laravel-admin-extensions/UEditor#4]
js里确实是有delEditor
第一次加载正常,跳转页面后
第二次加载富文本到最底下了,继续跳转页面后
第三次报错,delEditor这行报错
![image](https://user-images.githubusercontent.com/20037570/51369554-00106c80-1b2f-11e9-80d5-1129b542d43e.png)

另外一个项目也是用的,就没这样问题.也是很尴尬,确实找不到问题出在哪里.版本什么都一致

**Comment by moore0903** [comment]
找到解决方法了,要改只能去改库了,
将模板中的
`<script id="{{$id}}" name="{{$name}}" type="text/plain">{!! old($column, $value) !!}</script>`
更换成
`<textarea id="{{$name}}" name="{{$name}}" placeholder="{{ $placeholder }}" {!! $attributes !!} >{{ old($column, $value) }}</textarea>`
暂时能解决这个问题.但是具体什么原因导致的还不清楚

**Comment by codingyu** [comment]
一会我看看 还有个中文引号问题你有遇到么？

**Comment by moore0903** [comment]
中文引号没有遇到过问题.没办法重现
