### ISSUE TITLE
larval-admin

### ISSUE THREAD

**Issue by piaohan** [laravel-admin-extensions/UEditor#5]
laravel-admin  集成本扩展 能详细点不？ 按流程 发布后就不知道怎么用了。

**Comment by codingyu** [comment]
[https://laravel-admin.org/docs/zh/model-form-fields](https://laravel-admin.org/docs/zh/model-form-fields)
跟其他控件一样
前提 不要移除 editor 组件 [组件管理](https://laravel-admin.org/docs/zh/model-form-field-management.md)
```
// app\Admin\Controllers\UserController.php
/**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new User);

        $form->text('name', '姓名')->rules('required');
        $form->text('email', '邮箱')->rules('nullable|email');
        $form->editor('content');

        return $form;
    }
```

**Comment by piaohan** [comment]
@codingyu wangEditor 这个已经用过了，在多图片的时候，他因为是使用base64存储的，数据库字段改为longtext都存不下的。 所以 会选择现在的扩展UEditor。但是发现文档一半，官网没有相关的集成

**Comment by piaohan** [comment]
@codingyu editor 我尝试过不移除，发现没有效果的。所以后面我有尝试我的做法，虽然实现了，但是兼容性很差。

**Comment by codingyu** [comment]
@piaohan 没效果是什么样呢？ 界面上不显示？

**Comment by piaohan** [comment]
@codingyu 对，显示的是最早的
$form->editor('content');
这个显示的不是百度的那个编辑器
![image](https://user-images.githubusercontent.com/12056081/53705925-bc658e00-3e62-11e9-9fdf-9ade152a233e.png)

**Comment by codingyu** [comment]
@piaohan 不确定你那边是什么情况，我刚建了空项目，安装完是可以的

另外发现一个问题：admin.php 不写扩展的配置会报错， 这个我稍后会处理一下
