### ISSUE TITLE
按照你说的步骤安装不能正常使用

### ISSUE THREAD

**Issue by jingfengshi** [laravel-admin-extensions/UEditor#6]
资源加载不到

**Comment by codingyu** [comment]
参考：[overtrue/laravel-ueditor/issues/52](https://github.com/overtrue/laravel-ueditor/issues/52)
是 windows 下执行的么？

**Comment by jingfengshi** [comment]
是的，好像是文件发布的时候出问题了，没有发布成功

**Comment by codingyu** [comment]
试一下去掉引号或者使用双引号吧，我在 win10 下 power shell 没什么问题

**Comment by jingfengshi** [comment]
好的 多谢
